import Head from "next/head";
import { Layout } from "../components/layout";
import { HeroBanner } from "../components/blocks/heroBanner";
import video from "../assets/vid/reel.mp4";
import { Clients } from "../components/blocks/clients";
import Title from "../components/title";
import { Section } from "../components/util/section";
import { Container } from "../components/util/container";
import Work from "../components/blocks/work";
import WhatWeDoCards from "../components/blocks/whatWeDo";
import ContactForm from "../components/forms/contactForm";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroBanner
        sectionProps={{ offsetTop: false }}
        headline="Hatch Head is a digital product design agency."
        text="We're trusted by ambitious businesses and entrepreneurs to develop transformational ideas into tangible, valuable products."
        video={video}
        size="full"
        //containerProps={{ size: "full" }}
      />

      <Clients />

      <Section>
        <Container>
          <Title title="We help you with" className="mb-12" />

          <WhatWeDoCards className="mb-24" />
        </Container>
      </Section>

      <div className="bg-black bg-no-repeat bg-cover bg-center bg-[url('/img/black-abstract-bg.png')] bg text-white py-24 mb-48">
        <Container width="medium" className=" text-white text-center">
          <h1 className="text-lg md:text-2xl font-bold text-center mb-8">
            We provide the design behind our clients success
          </h1>
          <p className="text-center text-base md:text-lg text-neutral-400">
            We are designing for businesses, big or small so they can achieve
            whatever they aim to achieve.
          </p>
        </Container>
      </div>

      <div className="flex flex-col justify-center mb-12 lg:mb-24 container">
        <Title title="Projects" offsetDot />
      </div>

      <Work />

      <Section>
        <ContactForm />
      </Section>
    </Layout>
  );
}
